### ISSUE TITLE
Problem status with UE40H6200

### ISSUE THREAD

**Issue by michelebossa** [arturleao/samsungtv_custom#1]
Hi,
I'm using this component with my TV UE40H6200 but i have a problem with status of media player it is "on" when my TV is "off".

![image](https://user-images.githubusercontent.com/38975058/72663293-3f4af500-39f1-11ea-8729-7dac033c98d0.png)

There is something i can do?

Another things there is the possibility to send some extra command example KEY_CHUP or a single channel?

Thanks.

**Comment by arturleao** [comment]
This happens to me too even with the standard media player from Home Assistant, I assume its related with the fact that these tv's do not support wake on lan, either way I'll look into it.

Regarding extra channels, I believe it's possible yes, but I'm still not very familiar with the HA API so let me investigate further. Cheers and thanks for the feedback!

**Comment by michelebossa** [comment]
I have made a little modify into file media_player.py and now it is working better i'll hope can fix the problem. Try yourself

![image](https://user-images.githubusercontent.com/38975058/72664556-e6cf2400-39ff-11ea-8bc3-58e2e5f760f7.png)


![image](https://user-images.githubusercontent.com/38975058/72664608-475e6100-3a00-11ea-9e80-e7e5a2350e55.png)

Abouth the command there is these method

![image](https://user-images.githubusercontent.com/38975058/72664754-f2234f00-3a01-11ea-8d78-c58a35a98a21.png)

i have used this with mini-media-player and it is working.
![image](https://user-images.githubusercontent.com/38975058/72664762-036c5b80-3a02-11ea-82b9-3dc6a4ba1170.png)

`entity: media_player.samsung_tv_remote
shortcuts:
  buttons:
    - id: 1
      name: Rai 1
      type: channel
    - id: 2
      name: Rai 2
      type: channel
    - id: 3
      name: Rai 3
      type: channel
    - id: 4
      name: Rete 4
      type: channel
    - id: 5
      name: Canale 5
      type: channel
    - id: 6
      name: Italia 1
      type: channel
    - id: 43
      name: Rai Yoyo
      type: channel
  columns: 4
type: 'custom:mini-media-player'`

Thanks.

**Comment by Xitro01** [comment]
Someone with a UE48H5500AW here.
First of all @arturleao thanks alot for creating and sharing this great plug-in, the first one that actually works with H series Samsung TV's.

I have the same issue as described above. It says on while it's off. The fix by @michelebossa solved it, but it takes about 10 minutes before it shows as off, which isn't really how it's meant to be.
Any progress on fixing this issue? Maybe built in some kind of ping command to the IP address?

**Comment by arturleao** [comment]
Hi guys, glad this is working out for you, happy to help. Sorry about the delay but I've been busy with work and haven't got the time to look at this. Will try to get this fix in soon, although I'm not sure the change in the code is correct (even though the outcome looks correct)

**Comment by michelebossa** [comment]
Hi guys, I have tested with more accuracy and for me there is another problem after some time the TV don't respond at command  to fix i need to power off on home assistant the media player (The TV still power on) and after 1/2 minutes the status is reset to ON and i can command now the TV. (until after some time the TV didn't respond again)

I think there is some problem on connection occurred after some time maybe the pooling to check the status broke the connection with TV and i need to power off to reset the connection.

There is some check or modify to try to fix this problem?

Thanks.

**Comment by Xitro01** [comment]
I had some issues controlling my TV with Home Assistant as well. After turning it off in HA and wait till it was on again (in HA) I could use my volume buttons again after a little bit. This seems to be the same issue as @michelebossa has.

**Comment by Xitro01** [comment]
If you have these issues sorted it might also be very cool to have this add-on added to HOME ASSISTANT COMMUNITY STORE (HACS): https://hacs.xyz/docs/publish/start
So that we can easily keep your add-on up-to-date in our Home Assistant installations.

**Comment by asiersan** [comment]
Same problem, with a 55hu7500. This is the  only integration that works. But there is a state problem, and asqdescribed to use buttons i must waite.sometimes works randomly

**Comment by arigit** [comment]
HU8550 here - pairing works, controls work fine, turning off works fine. 

On/Off State detection is broken as reported above. 

Any chance to give the option to switch to "ping-based" state detection? I believe it is supported now in the samsung_tv_custom (original) component. It will work fine - In the past I had built myself a state tracker based on a ping sensor directly on HA. Looking forward to having this fix.

Thanks @arturleao  for sharing this.

**Comment by arigit** [comment]
Ping-based status test idea:

Testing: added a class method,

```
import subprocess

....

    def pingTV(self):
        """ping TV"""
        cmd = ['ping', '-c1', '-W2', self._host ]
        response = subprocess.Popen(cmd, stdout=subprocess.PIPE)
        stdout, stderr = response.communicate()
        if response.returncode == 0:   
            return True
        else:
            return False
```


And within send_key(self, key), I added a ping check

```
        # first try pinging the TV
        if not self.pingTV():
            self._state = STATE_OFF
            self.get_remote().close()
            self._remote = None
            return
```

**Comment by sermayoral** [comment]
Same behaviour here. It works, and the state seems to be fine, but after a couple of minutes commands don't work. It was tested in the UE50H6400 model.

@arturleao great jog doing our Samsung works in Home Assistant. This throws a lot of hope :-). As @Xitro01 says, you should make this custom available in HACS, in order to all HA users know this custom and he could help improving this. Maybe you should rename the custom to "samsungtv_encrypted_series" or something like that to differentiate it from @roberodin 's one.

@arigit thanks for your proposal. I think we should use the estandar samsungtv HA component method to do this. If your solution works, please, make a PR.

Thanks everybody!

**Comment by CsepregiArtur** [comment]
Hello

And works for how many days, I need to repair mine after 2-3 days

**Comment by arigit** [comment]
@CsepregiArtur in my case the "state" now stays in sync with reality (with the ping-based tracker), but other than that I see the same problem as everyone with the buttons stopping working and needing a TV Off > On cycle in HA in order to get back to work. When time allows I would take a look at the status update timer (trying to make it a little more frequent) and/or forcing a connecting re-initialization with every key (I wonder if this would take too long and make the integration less usable than now)

**Comment by magede** [comment]
Hi, I had the same issue with commands stopped working after a (short) while. Tested to disconnect after every command, but got a very slow experience (when hitting multiple commands, like stepping up volume). Added a timer that disconnects 10 seconds after a connect, which forces a reconnect on any later command. Ugly, but works without noticeable slowdown so an ok temporary solution for me 🙂

**Comment by arigit** [comment]
@magede do you mind posting the code snippets here of your solution? how you implemented the timer, and how you disconnect to force the re-connection

This solution would certainly fit my use case very well

**Comment by magede** [comment]
@arigit sure, here it is. In pysmartcrypto.py I added this:

`
def disconnectCallback(self):
    self.close()
`
And from within the init-function I started a timer as the connect
```
        ....
        self._host = host
        self._port = port
        self._connection = self.connect()

        # These two lines are the new ones
        self._timer = threading.Timer(10, self.disconnectCallback)
        self._timer.start()
```

Note: I also replaced the **_def update(self)_** function with the ping functionality mentioned above.

**Comment by arigit** [comment]
@magede thanks! works
I'll fork this and submit a PR including the ping-based status and disconnect timer

p.s PR submitted - I hope ppl in this discussion can test and confirm here whether this solves the problems

**Comment by sermayoral** [comment]
@arturleao with your permission, I've forked this repository to work on it. I have free time now and i would like to have my Samsung TV working as soon as possible. I suppose you haven't enough free time to add it to HACS, working on it, etc. I hope you do not mind :-)

I have added it to HACS (waiting for authorization of @ludeeus) and rename the component to avoid collisions of HACS.

@arigit. Could you make your pull request against https://github.com/sermayoral/ha-samsungtv-encrypted again?

**Comment by arturleao** [comment]
@sermayoral of course, this is the beauty of open source :) Thanks for taking the time to make it into HACS.  I will close this issue and we can continue discussion in your repository.

**Comment by sermayoral** [comment]
> 
> 
> @sermayoral of course, this is the beauty of open source :) Thanks for taking the time to make it into HACS. I will close this issue and we can continue discussion in your repository.

@arturleao thanks :-)

I wanna complete this component till the ends :-) 

Next target: I think I can get working the set_volume_level function in order to control SamsungTV volume level via Google Assistant or Alexa. I've changed the device_class in your code to be a TV. Now it appears in that way:

![photo_2020-03-09_13-11-18](https://user-images.githubusercontent.com/30116095/76211870-7c6c8000-6207-11ea-9a27-854487e8c0a8.jpg)

Feel free to contribute to this custom in the way you want :-)

Best Regards!
