### ISSUE TITLE
Invalid config for [media_player.samsungtv_custom]: [token] is an invalid option 

### ISSUE THREAD

**Issue by degraafm76** [arturleao/samsungtv_custom#2]
Hi there,

I copied the master branche in config\custom_components\samsungtv_custom and added the below config to configuration.yaml

  - platform: samsungtv_custom
    host: 192.168.200.40
    token: !secret samsung_token
    sessionid: !secret samsung_id
    port: "8080"

Token creation is succesfull

After restarting HA the following error message appears in the HA eventlog:

Invalid config for [media_player.samsungtv_custom]: [token] is an invalid option for [media_player.samsungtv_custom]. Check: media_player.samsungtv_custom->token. (See ?, line ?).

any idea?

**Comment by degraafm76** [comment]
Sorry my bad, i had another samsungtv_custom version in the folder config\custom_components\samsungtv_custom when i replaced it with this version its working. Maybe change the documentation to put the files in config\custom_components\samsungtv_custom?

**Comment by degraafm76** [comment]
Solution was:

- copy samsungtv_custom to custom_components folder
- restart HA
- add below settings to HA config
platform: samsungtv_custom
host: 192.168.200.40
token: !secret samsung_token
sessionid: !secret samsung_id
port: "8080"
- restart HA

**Comment by weis999** [comment]
I am receiving still this issue, after doing your solution. Can you please help me maybe out?
