### ISSUE TITLE
How to call "get_token.py" via hassio

### ISSUE THREAD

**Issue by Flop2006** [arturleao/samsungtv_custom#4]
How can I call the script in hassio?
I have no access to the command line.

**Comment by arturleao** [comment]
Are you running it in a VM? If so I can give you a step by step. Either way, you can download the package and put it in your config folder and then run the get_token.py in windows (you need to have python installed though)

**Comment by Flop2006** [comment]
hassio is an installation in an docker container.
So i tried to run get_token.py windows but get the 

`Traceback (most recent call last):
  File "C:\Users\Flop\Desktop\HASSIO\arturleao Samsung\samsungtv_custom-master\samsungtv_custom-master\get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "C:\Users\Flop\Desktop\HASSIO\arturleao Samsung\samsungtv_custom-master\samsungtv_custom-master\PySmartCrypto\pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "C:\Users\Flop\Desktop\HASSIO\arturleao Samsung\samsungtv_custom-master\samsungtv_custom-master\PySmartCrypto\crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'`

tried to install crypto via `pip install cryto` but no success.

**Comment by arturleao** [comment]
Make sure you have the correct command line: pip install crypto

**Comment by Flop2006** [comment]
Oh, sorry, that was just a typo in my previous post.
The installation was successful, but the error message was the same.
After further search I found that I used the module 'Pycryptodome' instead of 'Crypto', so I got one step further.
Now i get this error:
```
Traceback (most recent call last):
  File "C:\Users\Flop\Desktop\HASSIO\arturleao Samsung\samsungtv_custom-master\samsungtv_custom-master\get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "C:\Users\Flop\Desktop\HASSIO\arturleao Samsung\samsungtv_custom-master\samsungtv_custom-master\PySmartCrypto\pysmartcrypto.py", line 8, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
```
If I try to install websocket, I get an error message that Microsoft Visual C++ 14.0 is required...
A little too much effort just to get the token.

Is there a way to call the file automatically and write the token directly into a file?

**Comment by arturleao** [comment]
You have to install the websocket package the same way you did the crypto one. The whole package has these dependencies not just to get the token. For now it is how it is, but eventually I'll move this to a proper HA package that will install dependencies automatically. There is no way (that I know off) to call the file automatically and write the file into a file because there is a need for user interaction in the TV, so it's always a two step installation. Either way, those package dependencies are the same as the official HA samsung tv one, so if you had that installed at one point it should have installed the required packages.

**Comment by Flop2006** [comment]
The problems with the dependencies concern my Windows system on which I tried to call the token-script.
 
In HA I see no possibility to call the script.
Maybe someone else knows better.

**Comment by asiersan** [comment]
I use a vmware ubuntu image.

**Comment by arturleao** [comment]
There's a new plugin based on HACS, we should continue discussion there: https://github.com/sermayoral/ha-samsungtv-encrypted
